/*
 * TIMERS_config.h
 *
 *  Created on: Apr 8, 2023
 *      Author: Karim
 */

#ifndef TIMERS_REVISION_TIMERS_CONFIG_H_
#define TIMERS_REVISION_TIMERS_CONFIG_H_

/*
 TIMER0_NORMAL
 TIMER0_PHASECORRECT_PWM
 TIMER0_CTC
 TIMER0_FAST_PWM
 */
#define TIMER0_MODE 		TIMER0_FAST_PWM

/*
 TIMER0_NORMAL
 NON_PWM_TOGGLE_ON_COMPARE_MATCH
 NON_PWM_CLR_ON_COMPARE_MATCH
 NON_PWM_SET_ON_COMPARE_MATCH
 FAST_PWM_CLR_ON_COMPARE_MATCH_TOP
 FAST_PWM_SET_ON_COMPARE_MATCH_TOP
 PHASE_CORRECT_PWM_CLR_UP_SET_DOWN
 PHASE_CORRECT_PWM_CLR_DOWN_SET_UP
  */
#define TIMER0_COMPARE_MODE	 FAST_PWM_CLR_ON_COMPARE_MATCH_TOP

/*
 PS_0
 PS_8
 PS_64
 PS_256
 PS_1024
 EXTERNAL_CLK_SRC_FALLINGEDGE
 EXTERNAL_CLK_SRC_RISINGEDGE
 */
#define TIMER0_PRESCALER	PS_8

/*
 ENABLE
 DISABLE
 */
#define TIMER0_OVERFLOW_INTERRUPT_EN	DISABLE
#define TIMER0_CTC_INTERRUPT_EN			DISABLE

/*
TIMER2_NORMAL
TIMER2_PHASECORRECT_PWM
TIMER2_CTC
TIMER2_FAST_PWM
 */
#define TIMER2_MODE 					TIMER2_NORMAL
/*
TIMER2_CTC_TOGGLE
TIMER2_CTC_CLEAR
TIMER2_CTC_SET
TIMER2_FASTPWM_CLEAR
TIMER2_FASTPWM_SET
TIMER2_PHASECORRECT_CLEAR
TIMER2_PHASECORRECT_SET
 */
#define TIMER2_COMPARE_MODE	 TIMER2_NORMAL
/*
 PS_0
 PS_8
 PS2_32
 PS_64
 PS2_128
 PS_256
 PS_1024
 */
#define TIMER2_PRESCALER	PS2_8
/*
 ENABLE
 DISABLE
 */
#define TIMER2_OVERFLOW_INTERRUPT_EN	DISABLE
#define TIMER2_CTC_INTERRUPT_EN			DISABLE
/*
 TIMER2_INTERNAL_CLOCK
 TIMER2_EXTERNAL_CLOCK
 */
#define TIMER2_INTERNAL_EXTERNAL_CLOCK 	TIMER2_INTERNAL_CLOCK

#define TIMER1_PRESCALER	PS_64



#endif /* TIMERS_REVISION_TIMERS_CONFIG_H_ */
